name: android-ci

on:
  push:
    branches:
    - beta
    - main
  pull_request:
    branches:
    - beta
    - main
    - dev
  branch_protection_rule:
    types: [created, completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

    - name: Update apt
      run: sudo apt-get update -y

    - name: Install optipng
      run: sudo apt-get install optipng -y

    - name: Generate keys
      run: make generate

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17.X

    - name: Build the app
      run: ./gradlew assembleDebug

    - name: Upload apk
      uses: actions/upload-artifact@v3
      with:
        name: Debug apk
        path: app/build/outputs/apk/debug/app-debug.apk
