name: android-ci

on:
  push:
    branches:
    - beta
  pull_request:
    branches:
    - beta
  branch_protection_rule:
    types: [created, completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          key.jks
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

    - name: Install requirements
      run: |
        sudo apt-get update -y
        sudo apt-get install optipng -y

    - name: Prepare the signature key
      run: |
        if [ ! -f key.jks ]
        then
          echo "No signature key found, generating a random key..."
          make generate
        fi

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17.X

    - name: Build debug
      run: ./gradlew clean assembleDebug

    - name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
        name: Debug APK
        path: app/build/outputs/apk/debug/FBoard-v*.apk

    - name: Build release
      run: ./gradlew clean assembleRelease

    - name: Upload release APK
      uses: actions/upload-artifact@v3
      with:
        name: Release APK
        path: app/build/outputs/apk/release/FBoard-v*.apk
